# Project Information
site_name: "Kaushik"
docs_dir: public
site_url: https://www.thekaushikls.com
site_author: Kaushik L. S.
site_description: Computational Design Expert
dev_addr: 0.0.0.0:80

# The below folders (and files) are excluded from the the build process.
exclude_docs: |
  templates/
  work/

#region Site Footer
# Copyright Information
copyright: <a href="https://www.thekaushikls.com">&copy; 2018 - 2025 thekaushikls.com</a>

extra:
  generator: false
  analytics:
    provider: google
    property: G-WLL7NQBM4B
  
  social:
    - name: LinkedIn
      icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/thekaushikls

    - name: GitHub
      icon: fontawesome/brands/github
      link: https://www.github.com/thekaushikls

    - name: Email
      icon: fontawesome/solid/at
      link: mailto:kaushiklsk96+thekaushikls@gmail.com
        
  consent:
    title: Cookie Policy
    description: >-
      This site uses cookies to save visitor's theme preferences.
    actions:
      - accept
#endregion Site Footer

#region Extensions & Plugins
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true # Round Checkbox
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true

extra_css:
  - custom/stylesheets/styles.css

extra_javascript:
  - mkdocs/javascripts/mathjax.js
  - mkdocs/javascripts/polyfill.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  # Build (as HTML) for offline usage
  #- offline
  # Search Box
  #- search:
      # Query tokenization, allows searching special characters from code blocks
      #separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  #- autorefs
  # Built-In Blog
  - blog:
      blog_dir: blog
      blog_toc: true                        # Show Table of Contents on blog index
      draft: false                          # Publish posts marked as Draft
      draft_on_serve: false                 # Preview posts marked as Draft
      
      post_excerpt: required                # Always require an excerpt
      post_date_format: medium
      post_url_date_format: yyyy
      post_url_format: "{date}/{slug}"
      archive_date_format: yyyy
      archive_url_date_format: yyyy
      archive_url_format: "archive/{date}"

#endregion Extensions & Plugins

#region Theme Design
theme:
  name: material
  custom_dir: theme
  highlightjs: true

  # Typography
  text: Nunito
  code: Roboto Mono
  
  # Site Colors
  palette:
    # Color Scheme for Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode
      
    # Color Scheme for Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  # Icons
  logo: resources/Icon_256x256.png
  favicon: resources/Icon_256x256.ico
  icon:
    repo: fontawesome/brands/github
  
    # Icons for Admonitions
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/fire
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
#endregion Theme Design

# Additional Features
  features:    
    # Header
    - header.autohide         # Hide Header when scrolling

    # Search Box
    - search.suggest          # Suggestions in search box
    - search.highlight        # Highlights all occurences
    - search.share            # Enables button to copy search query

    # Navigation Bar / Path
    - navigation.instant      # Behaves as a single page application, faster content
    - navigation.top          # Back to top
    - navigation.tabs         # Displays a navigation menu below header
    - navigation.tracking     # URL tracks headers
    #- navigation.sections    # Displays folders as sections
    #- nativation.indexes     # Documents can be directly attached to sections
    #- navigation.expand      # Auto Expand everything
    - navigation.path         # Breadcrumbs
    - navigation.prune        # Optimizes site by not rendering the entire navigation list
    #- navigation.footer      # Navigation to next page in footer
    #- toc.integrate          # Combines Table of Contents with navigation list
    
    # Code Formatting
    - content.code.copy       # Copy copy button in code block
    #- content.code.select     # Enable line selection in code block
    #- content.code.annotate  # Tooltip from comment in code block
    #- content.action.edit    # Enables the 'Edit on GitHub' button
    #- content.action.view    # Enables the 'View source of this page' button
#endregion Theme Design