authors:
  thekaushikls:
    name: Kaushik L. S.
    description: "Software Developer"
    avatar: https://github.com/thekaushikls.png
    slug: https://www.github.com/thekaushikls
    url: https://www.linkedin.com/in/thekaushikls
